package com.fengqian.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseColumn<M extends BaseColumn<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setColumnName(java.lang.String columnName) {
		set("column_name", columnName);
	}

	public java.lang.String getColumnName() {
		return get("column_name");
	}

	public void setColumnDesc(java.lang.String columnDesc) {
		set("column_desc", columnDesc);
	}

	public java.lang.String getColumnDesc() {
		return get("column_desc");
	}

	public void setColumnImg(java.lang.String columnImg) {
		set("column_img", columnImg);
	}

	public java.lang.String getColumnImg() {
		return get("column_img");
	}

	public void setIsUp(java.lang.Integer isUp) {
		set("is_up", isUp);
	}

	public java.lang.Integer getIsUp() {
		return get("is_up");
	}

	public void setUpTime(java.util.Date upTime) {
		set("up_time", upTime);
	}

	public java.util.Date getUpTime() {
		return get("up_time");
	}

}
