package com.fengqian.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setIsUp(java.lang.Integer isUp) {
		set("is_up", isUp);
	}

	public java.lang.Integer getIsUp() {
		return get("is_up");
	}

	public void setUpTime(java.util.Date upTime) {
		set("up_time", upTime);
	}

	public java.util.Date getUpTime() {
		return get("up_time");
	}

	public void setColumnId(java.lang.Long columnId) {
		set("column_id", columnId);
	}

	public java.lang.Long getColumnId() {
		return get("column_id");
	}

	public void setColumnName(java.lang.String columnName) {
		set("column_name", columnName);
	}

	public java.lang.String getColumnName() {
		return get("column_name");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

}
