package com.fengqian.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("advice", "id", Advice.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("article_like", "id", ArticleLike.class);
		arp.addMapping("column", "id", Column.class);
		arp.addMapping("user", "id", User.class);
	}
}

