package com.fengqian.model;

import com.fengqian.model.base.BaseAdvice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Advice extends BaseAdvice<Advice> {
	public static final Advice dao = new Advice();
	public static final String TABLE_NAME="advice";
}
