package com.fengqian.model;

import com.fengqian.model.base.BaseArticle;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article();
	public static final String TABLE_NAME = "article";

	/**
	 * 根据栏目id获取文章数量
	 */
	public Integer getArticleCountByCol(Long id) {
		Record record= Db.findFirst("select count(*) count from " + TABLE_NAME + " where column_id=" + id);
		return record.getLong("count").intValue();
	}
}
