package com.fengqian.model;

import com.fengqian.model.base.BaseArticleLike;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleLike extends BaseArticleLike<ArticleLike> {
	public static final ArticleLike dao = new ArticleLike();
	public static final String TABLE_NAME="article_like";

	public Long getLikeCountByArt(Long id) {
		Record r=Db.findFirst("select count(*) count from "+TABLE_NAME+" where article_id="+id);
		return r.getLong("count");
	}
}
