package com.fengqian.model;

import com.fengqian.model.base.BaseColumn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Column extends BaseColumn<Column> {
	public static final Column dao = new Column();
	public static final String TABLE_NAME="test.column";
}
