package com.fengqian.model;

import com.fengqian.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	public static final String TABLE_NAME="user";
}
